language: node_js
node_js:
  - "10"
before_install:
  - npm i -g nyc
services:
  - postgresql
before_script:
  - psql -c 'create database games;' -U postgres
script:
  - npm run lint
  - npm run coveralls
notifications:
  email: false
